### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by PBL-markroelfsema** [openclimatedata/ndcs#4]
The NDC registry tool looks very interesting, but I am not able to install it. First, the makefile does not run if I execute 'make all' or 'make download'. Then I tried to install the packages manually (with pip), but installing 'pyicu' gives errors, as I seem to need all kinds of c++ libraries. Is there a way I can use the scripts without installing 'pyicu'?

**Comment by rgieseke** [comment]
What platform are you on and what error message do you get when running `make`?

pyicu is an optional sub-dependency, I think brought in through [normality](https://github.com/pudo/normality) which is used in [countrynames](https://github.com/alephdata/countrynames).

So the script should run without pyicu installed (just giving a warning).

**Comment by PBL-markroelfsema** [comment]
Thanks, that works indeed!

**Comment by rgieseke** [comment]
Closing, since you got it working! (I also updated the repo with the latest NDCs.)
